#AdiIRC Theme
#v1.0

CONF_color_1=255,255,255
CONF_color_2=0,0,0
CONF_color_3=0,0,127
CONF_color_4=0,147,0
CONF_color_5=255,0,0
CONF_color_6=127,0,0
CONF_color_7=156,0,156
CONF_color_8=252,127,0
CONF_color_9=255,255,0
CONF_color_10=0,252,0
CONF_color_11=0,147,147
CONF_color_12=0,255,255
CONF_color_13=0,0,252
CONF_color_14=255,0,255
CONF_color_15=127,127,127
CONF_color_16=210,210,210
CONF_color_17=0,0,0
CONF_color_18=56,96,194
CONF_color_19=82,155,19
CONF_color_20=0,0,0
CONF_color_21=56,96,194
CONF_color_22=255,255,255
CONF_color_23=0,0,0
CONF_color_24=211,86,3
CONF_color_25=82,155,19
CONF_color_26=56,96,194
CONF_color_27=255,255,255
CONF_color_28=0,0,0
CONF_color_29=255,255,255
CONF_color_30=0,0,0
CONF_color_31=0,0,0
CONF_color_32=0,0,0
CONF_color_33=0,0,0
CONF_color_34=0,0,0
CONF_color_35=0,0,0
CONF_color_36=160,160,160
CONF_color_37=0,0,0
CONF_color_38=211,86,3
CONF_color_39=0,0,0
CONF_color_40=0,0,0
CONF_color_41=0,0,0
CONF_color_42=0,0,0
CONF_color_43=211,86,3
CONF_color_44=201,164,14
CONF_color_45=201,164,14
CONF_color_46=56,96,194
CONF_color_47=56,96,194
CONF_color_48=56,96,194
CONF_color_49=0,0,127
CONF_color_50=56,96,194
CONF_color_51=255,255,255
CONF_color_52=0,0,0
CONF_color_53=0,0,255
CONF_color_54=171,171,171
CONF_color_55=196,85,40
CONF_color_56=255,255,255
CONF_color_57=255,255,255
CONF_color_58=255,255,255
CONF_color_59=0,0,0
CONF_color_60=0,0,0
CONF_color_61=0,0,0
CONF_color_62=0,0,0
CONF_color_63=211,86,3
CONF_color_64=56,96,194
CONF_color_65=82,155,19
CONF_color_66=51,153,255
CONF_color_67=255,255,255
CONF_color_68=192,192,192
CONF_color_69=0,0,0
CONF_color_70=0,0,0
CONF_color_71=0,0,0
CONF_color_72=0,0,0
CONF_color_73=0,0,0
CONF_color_74=0,0,0
CONF_color_75=0,0,0
CONF_color_76=192,192,192
CONF_color_77=56,96,194
CONF_color_78=192,192,192
CONF_color_79=160,160,160
CONF_color_80=160,160,160
CONF_usetimestamp=True
CONF_font=Verdana 9
CONF_timestamp=[%HH:%ii:%ss]
CONF_prefixsys=*
CONF_prefixuser=<$pnick>
CONF_prefixctcp=>
CONF_prefixemote=* $pnick
CONF_userlistfont=Verdana 9
CONF_userliststrip=False
CONF_userlistyourpre=True
CONF_userlistprew=0
CONF_userlistprey=0
CONF_userlistpreu=0
CONF_userlistpreo=0
CONF_userlistpreh=0
CONF_userlistprev=0
CONF_sidebarfontws=1
CONF_sidebarfontwc=0
CONF_sidebarfontwp=0
CONF_sidebarfontwt=0
CONF_sidebarfontwpr=0
CONF_sidebarfontwy=0
CONF_sidebarfontwco=0
CONF_sidebarfontwho=0
CONF_sidebarfontwv=0
CONF_sidebarfontwn=0
CONF_sidebarfont=Verdana 9
CONF_sidebarstrip=False
CONF_sidebarpre=True
CONF_sideshowicons=True

